include:
- project: tq-em/public/build/base
  file: ci/include.yml
  ref: v4.0.0

.test-settings:
  extends:
    - .gitlab-runner-tag
    - .image-ubuntu

# Jobs
Shell linter:
  extends: .lint-shell
  variables:
    SHELLCHECK_OPTIONS: -P lib

Check documentation:
  extends: .test-settings
  stage: test
  script: make docs

Integration Tests:
  extends: .test-settings
  stage: test
  script: make tests
